name: hayzay
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13834
title: hayzay begins again
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72660649-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaf9fc'
    - '#c4d8cd'
    - '#120e0b'
    - '#786a3e'
    - '#cfa961'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
